- job: Build
    displayName: Build Maven Project
    steps:
    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'pom.xml'
    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)
    - upload: $(Build.ArtifactStagingDirectory)
      artifact: drop

      jobs:  
- deployment: VMDeploy
  displayName: web
  environment:
    name:  myEnvironment
    resourceType: VirtualMachine
    tags: web1
  strategy:
    runOnce:
      deploy:
        steps:
        - script: echo my first deployment